pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-193
=> OZ-193: Removed temporary FHIR2 module dependency override.

.gitpod.dockerfile, .gitpod.yml
https://mekomsolutions.atlassian.net/browse/OZ-196
---
`envsubst` tool is missing on Gitpod environment.
Install `gettext-base` package.
Could be done by providing a custom Gitpod Dockerfile but when providing custom Dockerfile instructions, Gitpod takes ages to run (as it builds the image beforehand). The above solution appears faster.
---
⚠️ 2 commits: make sure to **squash** when merging.
=> OZ-196: Fix the Gitpod instructions

README.md
Update the README after the changes introduced by https://github.com/ozone-his/ozone-docker/pull/66
=> OZ-457: Update README to reference Nginx (and not Apache 2).

ozone-distro-parent/pom.xml
1. Ozone default files should be processed _before_ local files
2. Local files should be in ${project.basedir}/configs not ${project.parent.basedir}/configs.
=> Fix distro parent POM

distro/pom.xml, maven-commons/pom.xml, maven-parent/pom.xml, pom.xml
This PR implements the agreed-on naming conventions for the stuff that's currently in the repo. I've also done some very small POM refactors to remove duplicate data (verified with `mvn help:effective-pom`).
| Folder | GroupId | ArtifactId | Purpose |
| ------ | -------- | --------- | -------- |
| maven-parent | com.ozonehis | maven-parent | Parent project for Ozone implementations |
| maven-commons | com.ozonehis | maven-commons | Shared Maven configurations for Ozone |
I've also renamed the thing I was calling a "distro" to "implementation", so, e.g., ozone-cambodia is an "Ozone implementation project"
=> Rename subprojects according to agreed standards

distro/pom.xml, maven-parent/pom.xml, ozone-distro-parent/pom.xml, ozone-parent/pom.xml, pom.xml, scripts/assembly.xml, scripts/openmrs/frontend_assembly/build-openmrs-frontend.groovy, scripts/pom.xml
This is an attempt to fulfill OZ-462. I have not yet added docs, as there are some details I'm hoping to finalize.
**Assumptions:**
1. Machines running the distro have a recentish version Node / NPM (I think v16+) installed and available on the system PATH.
2. Ozone deployments do not actually need the customizations provided by spa-build-config.json.
**How this works:**
* Ozone now downloads the org.openmrs.distro:referenceapplication-frontend zip file and unpacks it in `$OZONE_DIR/configs/openmrs/frontend_assembly/reference-application-spa-assemble-config.json`
* An Ozone _distribution_ can provide a custom `spa-assemble-config.json` file in `$DISTRO_ROOT/configs/openmrs/frontend_assembly` that specifies their additions and removals.
* In an Ozone distribution, the …
=> OZ-462: Ozone distro to repackage the O3 frontend

maven-parent/pom.xml
The three ant run executions didn't really work as the condition property does not become a Maven property. This reworks things into a single Ant execution.
cc: @rbuisson
=> OZ-196: Fix OMOD renaming job

maven-parent/pom.xml
cc: @rbuisson Another thing I missed (added modules to /binaries instead of `/distro/binaries`.
=> Move modules to correct directory

.github/workflows/check-deps.yml
Issue: https://mekomsolutions.atlassian.net/browse/INFRA-407
- Update `check-deps` workflow to notify OCD3 only on dependency changes
This PR relates to https://github.com/mekomsolutions/shared-github-workflow/pull/30
=> INFRA-407: Update `check-deps` workflow to notify OCD3 only on dependency changes.

maven-parent/pom.xml
The `go-to-scripts-dir.sh` script needs to be run through Maven filtering. This used be handled, but was mistakenly dropped when we switched to using an artifact for this.
=> OZ-196: Properly filter scripts from scripts artifact

scripts/openmrs/frontend_assembly/build-openmrs-frontend.groovy
Move the step that cleans the output directory into a block that only executes when we are (re-)building the frontend, so that we don't accidentally clear it out by mistake.
=> OZ-462: Only clean output directory if needed

scripts/install-latest.sh
As per reported on Slack by @kdaud : https://mekomsolutions.slack.com/archives/G421UNF5L/p1710755159424749
PR is making sure that the file is renamed only when the file is timestamped, which is not consistently the case.
=> OZ-450: Fix the 'install-latest.sh' script

distro/configs/erpnext/initializer_config/item_price/insert_item_price.csv, distro/configs/erpnext/initializer_config/items/insert_item.csv
This PR does:
- Uncompress init SQL dump file to.sql to fix permission issue.
- Add Item missing data.
- Configure ERPNext Quotation Item with the custom field "ExternalID" which maps to ServiceRequest/MedicationRequest UUID.
=> OZ-464: Uncompress init sql dump and add missing item data.

maven-parent/pom.xml
In order to make setting up a new distro easier, we remove the default exclusions from the maven-parent. Most concrete distributions will end up with their own custom exclusions anyways, so this is not just redundant, but makes the experience of setting up Ozone more difficult.
=> OZ-196: Remove default exclusions from Maven parent so new Ozone distro is usable

distro/configs/superset/superset-init.sh, distro/configs/superset/superset_config.py
Makes changes needed to support importing dashboards into Superset https://mekomsolutions.atlassian.net/issues/KH-539
=> KH-539: Add support for importing Superset dashboards

scripts/install-stable.sh
https://mekomsolutions.atlassian.net/browse/OZ-632
This PR changes the install-stable.sh script to deprecate the use of CLI command for `dependency:get` and `dependency:copy` which misbehaves on releases.
See [Slack conversation](https://mekomsolutions.slack.com/archives/G421UNF5L/p1719338028599899).
This creates a temporary pom file to set an Ozone dependency and fetch it + export in a local ozone/ folder.
To test the PR:
```
curl -s https://raw.githubusercontent.com/ozone-his/ozone/OZ-632/scripts/install-stable.sh | bash /dev/stdin
```
=> OZ-632: install-stable.sh to temporarily create a pom file

scripts/install-stable.sh
Issue: https://mekomsolutions.atlassian.net/browse/OZ-627
This PR adds the change, if the `ozone/` folder exists, the script iterates to find the next available folder name with a numeric suffix (e.g., `ozone_1`, `ozone_2`). Also, adds informational message to guide the user on how to overwrite the existing `ozone/` folder if desired.
=> OZ-627: Update `install-stable.sh` to create new installation folder with numeric suffix if already exists

distro/pom.xml, scripts/erpnext/data_import/generate-import-script.groovy, scripts/pom.xml
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-529
This PR adds `generate-import-script.groovy` to `ozone-scripts` package and modifies the Maven build phase to `prepare-package`. The purpose of these changes is to enable the Groovy script to dynamically read configuration files from the target directory during the build process
=> OZ-529: Add `generate-import-script.groovy` to `ozone-scripts` and adjust phase for script execution

maven-archetype/src/test/resources/projects/it-basic/reference/scripts/.mvn/wrapper/maven-wrapper.properties
This PR updates maven wrapper distribution to latest released(`v3.9.9`)
=> OZ-672: Update maven wrapper distribution to `v3.9.9`

distro/configs/superset/security.py, distro/configs/superset/superset_config.py
Flask OIDC is not actively maintained, and this is causing dependency issues for Superset. This PR switches to using Authlib for SSO (https://mekomsolutions.atlassian.net/browse/OZ-671)
=> OZ-671: Update the Superset config to use authlib for SSO as Flask OIDC using old dependencies

.github/workflows/check-deps.yml
Associating to the Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-624 as it highlights the issue where the `check-deps` workflow time outs when there's a change. 
This PR Updates the `check-deps-timeout-minutes` parameter in `check-deps` GA workflow to 20 minutes. This change ensures that the dependency check process has sufficient time to complete, reducing the likelihood of timeout errors.
=> OZ-624: Increase check deps timeout to 20 minutes

distro/pom.xml, maven-parent/pom.xml, scripts/generate-ozone-info.groovy, scripts/pom.xml
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-627
- Added a new execution step in the `maven-antrun-plugin` to generate the `ozone-info.txt` file on the fly and another one in the `maven-resources-plugin` to copy the generated `ozone-info.txt` file to the final distro zip.
=> OZ-627: Add step to generate and copy Ozone info file

distro/configs/openmrs/frontend_config/ozone-frontend-config.json
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-698
This PR updates  `ozone/` to `configs/` because frontend assets/configs is now served at `/configs`
=> OZ-678: Update `ozone/` to `configs/` for serving frontend configs

maven-commons/pom.xml
- Upgrades openmrs-packager-maven-plugin to `v1.9.0-SNAPSHOT`.
=> OZ-698: Bump `openmrs-packager-maven-plugin` to `v1.9.0-SNAPSHOT`

distro/configs/openmrs/initializer_config/globalproperties/fhirproxy-privileges-props.xml, distro/configs/openmrs/initializer_config/privileges/privileges_stock-and-price.csv
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-708
This PR adds InventoryItem and ChargeItemDefinition privileges and configures `fhirproxy` module with the newly created privileges.
=> OZ-708: Add InventoryItem and ChargeItemDefinition privileges and configure `fhirproxy` module

maven-parent/pom.xml
Issue: https://mekomsolutions.atlassian.net/browse/OZ-573
This PR removes ERPNext from bundled docker.
=> OZ-573: Remove ERPNext from bundled docker

distro/configs/keycloak/realms/ozone-realm.json
Issue: https://mekomsolutions.atlassian.net/browse/OZ-671
This PR makes enabling/disabling of Superset client configurable.
=> OZ-671: Make enabling/disabling of Superset client configurable

distro/pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-785
=> OZ785: Update FHIR Proxy version to 1.0.0

distro/configs/odoo/initializer_config/setting/ir.config.parameter.xml
This is a follow-up to an issue we manually fixed for HSC where PDFs took too long to generate When the server could not access the Internet
=> HSC-380: Fix Odoo report printing timeout issue when server does not have Internet access

maven-parent/pom.xml
JIRA: https://mekomsolutions.atlassian.net/browse/HSC-402
With this PR the plugin will look for all the `*.env` files in `scripts` directory and merge them according to names
Example:
Haiti  (Parent Distro) env file should be named `ozoneb.env`
HSC (Child Distro) env file should be named `ozonea.env`
So the order of merging will be `.env` then `ozoneb.env` then `ozonea.env`
Meaning the merge happens in reverse order.
=> OZ-402: Add build step to merge `.env` files in `maven-parent`

distro/pom.xml
Issue: https://mekomsolutions.atlassian.net/browse/OZ-874
This PR bumps OpenMRS fhir2 module to `v2.3.0`
=> OZ-874: Use fhir2 module `v2.3.0`

scripts/install-stable.sh
As per Slack conversation: https://openmrs.slack.com/archives/C02PYQD5D0A/p1744730755964619
> The script should be pointing to the latest stable
=> OZ-841: 'install-stable.sh' to point to 1.0.0-alpha.13

distro/configs/openmrs/initializer_config/globalproperties/oauth2-login-props.xml
Issue: https://mekomsolutions.atlassian.net/browse/OZ-935
This PR updates the OAuth2 login redirect URI to `/spa/login/location`.
Previously, after a successful login, users were first redirected to the home page and then to the location picker. As a result, home page esm apps attempted to load before the user's location is set, causing network requests to fail due to the location being undefined.
=> OZ-935: Update OAuth2 login redirect URI to `/spa/login`

distro/configs/odoo/initializer_config/models/ir.model.1000.csv, distro/configs/odoo/initializer_config/models/ir.model.2000.csv, distro/configs/odoo/initializer_config/models/ir.model.3000.csv
https://mekomsolutions.atlassian.net/browse/OZ-962
=> OZ-962: Odoo custom fields `x_customer_weight` and `x_customer_dob` not created following Odoo 17 upgrade

.github/workflows/ci.yml
The validator is broken by the addressHierarchy domain and with the `3.5.0` refApp upgrade. We have decided to remove the `-Pvalidator` arg from the CI until a fix is made on the validator module.
=> Disable OpenMRS configuration validator from CI

distro/configs/keycloak/realms/ozone-realm.json
Fixes an issue accessing the Accounts page for Ozone users by adding + to the client's web origins which allows only valid redirect urls
=> HIS-19: Add web origins to `account-console` KC client 

maven-archetype/src/main/resources/archetype-resources/pom.xml, maven-archetype/src/test/resources/projects/it-basic/reference/pom.xml
Issue: https://mekomsolutions.atlassian.net/browse/OZ-898
This PR removes activation of the OpenMRS validator profile in Ozone Archetype.
=> OZ-898: Remove activation of the OpenMRS validator profile in Ozone Archetype
