ozone-his/ozone

pom.xml
=> OZ-49: Adding Common Reports + Patient Summary modules.

pom.xml
Ticket: https://github.com/ozone-his/ozonepro-distro/pull/8
=> OZ-49: Upping some released artifacts to released versions.

pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-109
=> OZ-109: Normalize artifact group metadata defined in POM

pom.xml
=> OZ-49: Ozone Config and Odoo Iniz set to release versions.

pom.xml
=> OZ-49: Bumping ozone-config to 1.1.0-SNAPSHOT

pom.xml
=> OZ-49: Removing Serialization XStream and Reference Demo Data overrides.

README.md
Refer to https://mekomsolutions.atlassian.net/browse/OZ-132
=> OZ-49: Correcting typos in main README.

pom.xml
This PR is updating artefacts making up moving parts to their SNAPSHOT versions (_Common Reports_ and _Ozone Configuration_).
=> OZ-49: Using bleeding edge Common Reports and Ozone Config.

pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-142
=> OZ-142: Updating SNAPSHOTs to Released versions

pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-142
=> OZ-142: Upped Ozone Config to 1.3.0 + Override FHIR2 module with version 1.10.0 timestamped.

.github/workflows/build-test.yml, pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-172
=> OZ-172: OpenMRS Config to be Iniz-validated at Maven integration-test phase.

pom.xml
https://mekomsolutions.atlassian.net/browse/TLC-139
=> TLC-139: CI validation to be done in build directory

README.md
Since we renamed the repository, we do need to update the README
=> OZ-354: Update README.md with renamed repos.

.gitignore, distro/pom.xml, ozone-distro-parent/pom.xml, ozone-parent/pom.xml, pom.xml
@rbuisson So, part of our discussion was around having a parent POM for Ozone. This actually creates two, one specifically just to ensure plugin versions are the same across projects (so now `ozone` and `ozone-distro` inherit from this) and one that's the actual parent POM for "actual" distributions.
With this, the Kenya distribution POM can be reduced to:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
<modelVersion>4.0.0</modelVersion>
<parent>
<groupId>com.ozonehis</groupId>
<artifactId>ozone-distro-parent</artifactId>
<version>1.0.0-SNAPSHOT</version>
</parent> …
```
=> OZ-196: Add parent POMs

ozone-distro-parent/pom.xml, ozone-parent/pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-196
=> OZ-196: Updated POMs with Distribution Management settings.

.github/workflows/ci.yml
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-472
Merges the release and pre-release into one GA job.
=> OZ-472: Merge pre-release and release GitHub Actions jobs.

maven-archetype/pom.xml, maven-archetype/src/main/resources/archetype-resources/pom.xml, maven-archetype/src/test/resources/projects/it-basic/reference/pom.xml
Should fix the release build failure.
=> Only run validator on JDK 8

distro/pom.xml
Ticket → [OZ-484](https://mekomsolutions.atlassian.net/browse/OZ-484)
[OZ-484]: https://mekomsolutions.atlassian.net/browse/OZ-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OZ-484: Use O3 Ref App 3.0.0-beta.17

distro/pom.xml
Ticket → [OZ-484](https://mekomsolutions.atlassian.net/browse/OZ-484)
[OZ-484]: https://mekomsolutions.atlassian.net/browse/OZ-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OZ-484: Use O3 Ref App 3.0.0-beta.18

distro/pom.xml
References:
* https://mekomsolutions.atlassian.net/browse/OZ-448?focusedCommentId=43408
* https://mekomsolutions.slack.com/archives/G421UNF5L/p1712153514804599?thread_ts=1712147939.840789&cid=G421UNF5L
=> Bumped Common Reports version to 1.5.0-SNAPSHOT.

distro/pom.xml
- Add `eip-erpnext-openmrs` routes
=> OZ-464: Add `eip-erpnext-openmrs` routes JAR.

scripts/install-stable.sh
Ticket → [OZ-526](https://mekomsolutions.atlassian.net/browse/OZ-526)
[OZ-526]: https://mekomsolutions.atlassian.net/browse/OZ-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OZ-526: Update install-stable.sh script to point to alpha.10

distro/pom.xml
Ticket → [OZ-571](https://mekomsolutions.atlassian.net/browse/OZ-571)
[OZ-571]: https://mekomsolutions.atlassian.net/browse/OZ-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OZ-571: Use O3 Ref App 3.0.0-beta.20

distro/pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-625
=> OZ-625: Use O3 Ref App 3.0.0-beta.21

scripts/install-stable.sh
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-611
=> OZ-611: Update 'install-stable.sh' script to point to 1.0.0-alpha.11

distro/pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-670
=> OZ-670: Use O3 Distro EMR `3.2.0-SNAPSHOT`

distro/configs/superset/security.py
Updating of user roles from Keycloak was broken after the recent switch to `authlib` as the OIDC library. This PR fixes the issue and is part of https://mekomsolutions.atlassian.net/browse/OZ-671
=> OZ-671: Update Superset user roles from Keycloak at login

distro/pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-720
=> OZ-720: Use O3 Ref App 3.3.0-SNAPSHOT

distro/configs/superset/security.py
https://mekomsolutions.atlassian.net/browse/OZ-683
=> OZ-683: Skip logout confirmation page

maven-archetype/src/test/resources/projects/it-basic/reference/README.md
Reference comment: https://github.com/ozone-his/ozone/pull/103#discussion_r1886743868
=> OZ-340: `maven-archetype` README as per Ozone's rebranding

maven-archetype/src/main/resources/archetype-resources/README.md, maven-archetype/src/test/resources/projects/it-basic/reference/README.md
Ref to slack convo: https://mekomsolutions.slack.com/archives/G421UNF5L/p1734336517727929
=> OZ-340: Align `maven-archetype` generated READMEs

distro/configs/keycloak/themes/carbon/login/resources/css/styles.css
https://mekomsolutions.atlassian.net/browse/OZ-771
=> OZ-771: Remove background color from password visibility toggle

distro/pom.xml
This PR updates paths in distro POM to correct OpenMRS config and module directories
Updated dirs:
- https://github.com/openmrs/openmrs-distro-referenceapplication/blob/main/distro/pom.xml#L288
=> OZ-1: Update OpenMRS configs & modules path to correct directories

distro/configs/openmrs/frontend_config/ozone-frontend-config.json
JIRA: https://mekomsolutions.atlassian.net/browse/OZ-813
=> OZ-813: Add Orthanc PACS in App Drawer

distro/pom.xml
https://mekomsolutions.atlassian.net/browse/OZ-790
=> OZ-790: Use Ref App 3.2.1

distro/pom.xml
Issue: https://mekomsolutions.atlassian.net/browse/OZ-832
This PR adds Ozone Analytics Queries into Ozone FOSS
=> OZ-832: Add Ozone Analytics Queries into Ozone FOSS

.gitpod.yml
JIRA: https://mekomsolutions.atlassian.net/browse/OZ-884
=> OZ-884: Add port description for Orthanc

scripts/openmrs/frontend_assembly/build-openmrs-frontend.groovy
This PR updates openmrs version in assemble command if it is overridden in `spa-assemble-config.json`
=> Update OpenMRS version dynamically in assemble command

distro/configs/keycloak/demo/users.json, distro/configs/keycloak/realms/ozone-realm.json
Issue: https://mekomsolutions.atlassian.net/browse/OZ-349
Demo users to be created by `ozone-demo-data` service
=> OZ-349:  Use `ozone-demo-data` service to create demo users

distro/configs/keycloak/demo/users.json
This PR updates Jdoe's client role for Superset from Gamma to Admin
=> OZ-349: Update Jdoe's client role for Superset from Gamma to Admin

distro/configs/openmrs/frontend_config/ozone-frontend-config-sso.json
Issue: https://mekomsolutions.atlassian.net/browse/HSC-449
This PR adds "Account Management" external link to the app menu
=> HSC-449: Add "Account Management" external link to app menu

scripts/install-stable.sh
Part of another work stream: https://mekomsolutions.atlassian.net/browse/OZ-279 to improve the implementation guide.
Another possible ticket for this: https://mekomsolutions.atlassian.net/browse/OZ-775
=> OZ-279 'install-latest.sh' to suggest running with Ozone with SSO

distro/configs/keycloak/realms/ozone-realm.json
https://mekomsolutions.atlassian.net/browse/OZ-675
=> OZ-675: Logout from the IdP should logout from all apps

distro/pom.xml
Issue: https://mekomsolutions.atlassian.net/browse/OZ-825
This PR updates Odoo initializer artifactId to `odoo-initializer`.
=> OZ-825: Update Odoo initializer artifactId to `odoo-initializer`

distro/binaries/odoo/addons/auth_oidc/controllers/main.py, distro/binaries/odoo/addons/auth_oidc/models/auth_oauth_provider.py, distro/binaries/odoo/addons/auth_oidc/models/res_users.py, distro/binaries/odoo/addons/auth_oidc/views/auth_oauth_provider.xml
Updates to theses files from the addon's repo were missing in the Odoo binaries folder for the addon
=> OZ-952: Update 'auth_oidc' to latest version

maven-parent/pom.xml, scripts/openmrs/bundled-docker/generate-bundled-docker-compose.groovy
Issue: https://openmrs.atlassian.net/browse/HIS-18
This PR:
- Adds the ability to override default bundled docker template.
- Improves error handling
=> HIS-18: Add the ability to override default bundled docker template and improve error handling

maven-parent/pom.xml, scripts/openmrs/bundled-docker/generate-bundled-docker-compose.groovy
Issue: https://openmrs.atlassian.net/browse/HIS-19
This adds:
- The ability to generate one self-contained Docker Compose SSO file.
- Enable or disable SSO via a property.
This PR depends on #154
=> HIS-19: Enable SSO based on a property + generate a self-contained SSO Docker Compose file

distro/pom.xml
This PR update common reports module to version `1.6.0-SNAPSHOT`
=> Update common reports OpenMRS module to `v1.6.0-SNAPSHOT`

distro/pom.xml, maven-parent/pom.xml
Issue: https://mekomsolutions.atlassian.net/browse/OZ-838
This PR adds Maven steps to copy OpenMRS frontend defined in Ref App's Content packages
=> OZ-838: Add Maven build steps to copy and rename OpenMRS frontend configurations

scripts/openmrs/bundled-docker/update-docker-compose-env-defaults.groovy
Issue: https://openmrs.atlassian.net/browse/HIS-37
This PR updates `update-docker-compose-env-defaults.groovy` to correctly inject default values for environment variables in a Docker Compose file, including lines with multiple variables. It also removes unnecessary single quotes and backslashes from substituted values.
=> HIS-37: Set env var defaults for multi-var lines without extra quotes or escapes
